name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-auto-assign:
    name: "Auto-assign Reviewers to PR #${{ github.event.pull_request.number }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: "Check if PR is from a fork"
        run: |
          if [ "$PR_HEAD_REPO" != "$PR_BASE_REPO" ]; then
            echo "⚠️ Pull request is from a fork — skipping assignee assignment (no write permissions)."
            exit 0
          fi
        env:
          PR_HEAD_REPO: "${{ github.event.pull_request.head.repo.full_name }}"
          PR_BASE_REPO: "${{ github.event.pull_request.base.repo.full_name }}"

      - name: "Checkout Repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          persist-credentials: false

      - name: "Assign Reviewers"
        uses: netcracker/qubership-workflow-hub/actions/pr-assigner@5a557213e92e3d22d0292330c4817c82af6704d2 #2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
